import type { CardDef } from "./types.js";

// Catalogue des cartes. Les stats sont volontairement simplifiées et
// équilibrées "à la main" pour que les parties durent ~2-3 minutes.
export const CARDS: Record<string, CardDef> = {
  knight: {
    id: "knight",
    name: "Chevalier",
    cost: 3,
    count: 1,
    kind: "troop",
    hp: 660,
    damage: 79,
    attackRange: 1.2,
    attackCooldownS: 1.1,
    moveSpeed: 1.0,
    aggroRange: 5.5,
    targets: "any",
    splashRadius: 0,
    radius: 0.5,
    color: 0x9aa4b2,
  },
  archers: {
    id: "archers",
    name: "Archères",
    cost: 3,
    count: 2,
    kind: "troop",
    hp: 125,
    damage: 42,
    attackRange: 5.0,
    attackCooldownS: 0.9,
    moveSpeed: 1.0,
    aggroRange: 5.5,
    targets: "any",
    splashRadius: 0,
    radius: 0.4,
    color: 0xf59e0b,
  },
  goblins: {
    id: "goblins",
    name: "Gobelins",
    cost: 2,
    count: 3,
    kind: "troop",
    hp: 80,
    damage: 47,
    attackRange: 1.0,
    attackCooldownS: 0.7,
    moveSpeed: 1.6,
    aggroRange: 5.5,
    targets: "any",
    splashRadius: 0,
    radius: 0.35,
    color: 0x22c55e,
  },
  giant: {
    id: "giant",
    name: "Géant",
    cost: 5,
    count: 1,
    kind: "troop",
    hp: 2000,
    damage: 120,
    attackRange: 1.2,
    attackCooldownS: 1.5,
    moveSpeed: 0.7,
    aggroRange: 0, // ne dévie jamais : fonce sur les bâtiments
    targets: "buildings",
    splashRadius: 0,
    radius: 0.7,
    color: 0xf97316,
  },
  musketeer: {
    id: "musketeer",
    name: "Mousquetaire",
    cost: 4,
    count: 1,
    kind: "troop",
    hp: 340,
    damage: 100,
    attackRange: 6.0,
    attackCooldownS: 1.0,
    moveSpeed: 1.0,
    aggroRange: 6.5,
    targets: "any",
    splashRadius: 0,
    radius: 0.45,
    color: 0xef4444,
  },
  fireball: {
    id: "fireball",
    name: "Boule de feu",
    cost: 4,
    count: 0,
    kind: "spell",
    hp: 0,
    damage: 0,
    attackRange: 0,
    attackCooldownS: 0,
    moveSpeed: 0,
    aggroRange: 0,
    targets: "any",
    splashRadius: 0,
    radius: 0,
    color: 0xdc2626,
    spellRadius: 2.5,
    spellDamage: 340,
  },
};

/** Ordre d'affichage dans la barre de cartes. */
export const CARD_ORDER = ["knight", "archers", "goblins", "musketeer", "giant", "fireball"];
